package br.senai.sp.menu.restaurante.errors;

public enum ExceptionCode {
    API_FIELDS_INVALID,
    INTERNAL_SERVER_ERROR,
    ENTITY_NOT_FOUND,
    DUPLICATED_RESOURCE,
    EMAIL_NOT_SENT,
    UNAUTHORIZED,
    AUTHENTICATION_TOKEN_CREATION_ERROR,
    FORBIDDEN,
    EXPIRED_TOKEN,
    USED_TOKEN,
    BAD_CREDENTIALS,
    INVALID_REQUEST_EXCEPTION,
    JSON_MAPPING_ERROR,
    EMAIL_NOT_VALIDATED,
    INVALID_PASSWORD_RECOVERY_CODE,
    IMAGE_FILE_REQUIRED,
    EMPTY_FILE,
    UNEXPECTED_ERROR_DURING_IMAGE_MANIPULATION,
}
